export const GET_COLORS = 'GET_COLORS';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_FEEDBACKS = 'GET_FEEDBACKS';
export const GET_PROJECTS = 'GET_PROJECTS';
export const SHOW_PROJECT = 'SHOW_PROJECT';
